### ISSUE TITLE
Pick format for *-block

### ISSUE THREAD

**Issue by abingham** [sixty-north/style-guide#1]
Things like else-block, except-block, etc. We should pick a format.

**Comment by abingham** [comment]
@rob-smallshire I think that for symmetry with e.g. for-loop we should use *-block without backticks around the * portion.

**Comment by rob-smallshire** [comment]
Yes, I agree.  Same goes for if-statement, etc.  I think the essence of the rule is that if we can 'nounify' the keyword by joining it to a real noun with a hyphen we don't need the backticks. We should use the backpacks, however, if it's a standalone keyword in prose, to avoid grammatical weirdness.

**Comment by abingham** [comment]
I've over-engineered a solution this in 78d73be423fd8ff44a8e2920a0fdee1293a2234f.

There's now a Python script which generates the rules for loops and blocks. 

I've [asked the vale developers](https://github.com/ValeLint/vale/issues/45) if there's a better way to do this using vale.
