### ISSUE TITLE
Inherit from vs. subclass

### ISSUE THREAD

**Issue by abingham** [sixty-north/style-guide#2]
Do we need to distinguish between and/or prefer one of "inherit from" and "subclass" over the other?

**Comment by rob-smallshire** [comment]
Yes we do. In Python it's possible to subclass a virtual base class without inheriting from it. That said, the verbing of subclass is pretty ugly in my view and we should perhaps it where possible.

**Comment by abingham** [comment]
I've added a rule in 25983de3c114d350a7ef0467f97427f0088a8555 to help us prefer "inherit" over "subclass".
